//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Участники
    {
        public System.Guid ID_участника { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
        public string E_mail { get; set; }
        public string Телефон { get; set; }
    }
}
